services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: wib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - wib_pg_data:/var/lib/postgresql/data

volumes:
  wib_pg_data:

