services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cian
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - cian_pg_data:/var/lib/postgresql/data

volumes:
  cian_pg_data:

