services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: amazon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - amazon_pg_data:/var/lib/postgresql/data

volumes:
  amazon_pg_data:

